### ISSUE TITLE
本插件似乎与Python语言支持冲突

### ISSUE THREAD

**Issue by Wakaki-Houmikan** [beishanyufu/ime-and-cursor#10]
您好！我刚刚安装了这个插件，发现它似乎与Python语言支持插件冲突，只要我disable了这个插件，问题就能解决。

启动ime-and-cursor时，右下角弹窗报错如下：
——————————————————————————————————————
Connection to server got closed. Server will not be restarted.
——————————————————————————————————————

OUTPUT - Python Langrage Serve里的报错如下：
——————————————————————————————————————
2023-12-09 15:46:21.895 [info] [Error - 3:46:21 PM] Server process exited with code 1.
2023-12-09 15:46:21.895 [info] [Error - 3:46:21 PM] Connection to server got closed. Server will not be restarted.
2023-12-09 15:46:21.895 [info] [Error - 3:46:21 PM] Handling connection close failed
2023-12-09 15:46:21.895 [info] TypeError: e.clear is not a function
    at _.cleanUp (c:\Users\mikan\.vscode\extensions\ms-python.python-2023.23.13391009\out\client\extension.js:2:2396933)
    at _.handleConnectionClosed (c:\Users\mikan\.vscode\extensions\ms-python.python-2023.23.13391009\out\client\extension.js:2:2401357)
    at _.handleConnectionClosed (c:\Users\mikan\.vscode\extensions\ms-python.python-2023.23.13391009\out\client\extension.js:2:2562326)
    at c:\Users\mikan\.vscode\extensions\ms-python.python-2023.23.13391009\out\client\extension.js:2:2400783
    at o.invoke (c:\Users\mikan\.vscode\extensions\ms-python.python-2023.23.13391009\out\client\extension.js:2:2347461)
    at s.fire (c:\Users\mikan\.vscode\extensions\ms-python.python-2023.23.13391009\out\client\extension.js:2:2348226)
    at te (c:\Users\mikan\.vscode\extensions\ms-python.python-2023.23.13391009\out\client\extension.js:2:2333858)
    at o.invoke (c:\Users\mikan\.vscode\extensions\ms-python.python-2023.23.13391009\out\client\extension.js:2:2347461)
    at s.fire (c:\Users\mikan\.vscode\extensions\ms-python.python-2023.23.13391009\out\client\extension.js:2:2348226)
    at d.fireClose (c:\Users\mikan\.vscode\extensions\ms-python.python-2023.23.13391009\out\client\extension.js:2:2356086)
    at ChildProcess.<anonymous> (c:\Users\mikan\.vscode\extensions\ms-python.python-2023.23.13391009\out\client\extension.js:2:2368438)
    at ChildProcess.emit (node:events:525:35)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
——————————————————————————————————————

之后我每在.py文件中输入或删除一个字符就会新出现一段这种报错：
——————————————————————————————————————
........
2023-12-09 15:41:13.182 [info] [Error - 3:41:13 PM] Sending document notification textDocument/didChange failed
2023-12-09 15:41:13.182 [info]   Message: Client is not running
  Code: -32096 
2023-12-09 15:41:16.396 [info] [Error - 3:41:16 PM] Sending document notification textDocument/didSave failed.
2023-12-09 15:41:16.396 [info]   Message: Client is not running
  Code: -32096 
2023-12-09 15:41:16.848 [info] [Error - 3:41:16 PM] Notify file events failed.
2023-12-09 15:41:16.848 [info]   Message: Client is not running
  Code: -32096 
.......
——————————————————————————————————————

我的系统是Windows10，使用的VSCode版本是1.84.2，Python语言支持和ime-and-cursor都是最新版本，输入法是Windows自带的输入法，已按照说明进行配置。此外，我并没有对这个插件进行任何改动或设置。

谢谢！

**Comment by beishanyufu** [comment]
复现了你遇到的问题。
又试了几款别的插件，如 Hex Editor, Git Graph, vim, 也都会导致 python 插件报同样的错。
最后我装了一个极简的 “hello world” 的插件，也未能幸免。
所以基本可以断定是 python 插件本身存在问题。
解决办法：
先安装/启用 ime and cursor，再安装/启用 python 插件；
或者更简单的，重启一下 vscode。

**Comment by Wakaki-Houmikan** [comment]
> 复现了你遇到的问题。 又试了几款别的插件，如 Hex Editor, Git Graph, vim, 也都会导致 python 插件报同样的错。 最后我装了一个极简的 “hello world” 的插件，也未能幸免。 所以基本可以断定是 python 插件本身存在问题。 解决办法： 先安装/启用 ime and cursor，再安装/启用 python 插件； 或者更简单的，重启一下 vscode。

谢谢！重启确实解决了问题。
