### ISSUE TITLE
使用shift+空格切换输入法提示"command 'ime-and-cursor.switch' not found"

### ISSUE THREAD

**Issue by longforrich** [beishanyufu/ime-and-cursor#2]
vscode 1.81
配置
```
    "ime-and-cursor.EnglishIM": 1033,
    "ime-and-cursor.cursorStyle.English": "Line",
    "ime-and-cursor.ChineseIM": 2052,
    "ime-and-cursor.cursorStyle.Chinese":"Underline",
    "ime-and-cursor.obtainIMCmd": "c:\windows\system32\im-select.exe",
    "ime-and-cursor.switchIMCmd": "c:\windows\system32\im-select.exe {im}",
```
发现一句跟此插件有关系的日志
```
2023-09-04 13:28:18.787 [error] Activating extension beishanyufu.ime-and-cursor failed due to an error:
2023-09-04 13:28:18.787 [error] TypeError: vscode.workspace.getConfiguration(...).get(...)?.trim is not a function
	at getConfiguration (c:\Users\Administrator\.vscode\extensions\beishanyufu.ime-and-cursor-1.0.0\out\extension.js:25:87)
	at activate (c:\Users\Administrator\.vscode\extensions\beishanyufu.ime-and-cursor-1.0.0\out\extension.js:96:5)
	at Dn.eb (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:13102)
	at Dn.db (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:12816)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:10913
	at async p.n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:6206)
	at async p.m (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:6169)
	at async p.l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:5626)
```

**Comment by beishanyufu** [comment]
输入法的id类型应该是字符串，也就是要像下面这样加上引号：

    "ime-and-cursor.ChineseIM": "2052",
    "ime-and-cursor.EnglishIM": "1033",

改好后重启一下vscode应该就可以了。

**Comment by beishanyufu** [comment]
另外注意到你的配置中如下两项，目录分隔使用的是单的反斜杠：

    "ime-and-cursor.obtainIMCmd": "c:\windows\system32\im-select.exe",
    "ime-and-cursor.switchIMCmd": "c:\windows\system32\im-select.exe {im}",

由于反斜杠在json字符串中被用作转义提示符，所以正确的写法应该是使用双反斜杠，如：

    "ime-and-cursor.obtainIMCmd": "c:\\windows\\system32\\im-select.exe",
    "ime-and-cursor.switchIMCmd": "c:\\windows\\system32\\im-select.exe {im}",

以上说明针对的是直接编辑settings.json文件的情况，若使用VSCcode的图形化设置界面进行设置则只需使用单的反斜杠。

**Comment by longforrich** [comment]
感谢指出，可以在本地工作了。
但是........它被安装到了远端主机上了，在使用远程开发时，不能工作。
![image](https://github.com/beishanyufu/ime-and-cursor/assets/53457069/139b9288-86a1-473e-bd7a-fa48a2c352ca)

**Comment by beishanyufu** [comment]
这题我不会，需要研究一下。

**Comment by beishanyufu** [comment]
发现从你那边关闭了issue，是问题已经解决了吗？
我学习了一下vscode远程连接开发，没实操。我的判断是，因为所涉及的到的操作（查询和修改输入状态，更新光标样式）都只涉及本地，所以不管是否连接远程进行开发，此插件都应该装在本地。

**Comment by longforrich** [comment]
> 发现从你那边关闭了issue，是问题已经解决了吗？ 我学习了一下vscode远程连接开发，没实操。我的判断是，因为所涉及的到的操作（查询和修改输入状态，更新光标样式）都只涉及本地，所以不管是否连接远程进行开发，此插件都应该装在本地。

哈，看到上文的“这题我不会，需要研究一下”，就关掉了以免打扰。我看到了changelog里说可以远程了，确实工作在本地，但好像还是切换困难....我会整理一下来汇报

**Comment by beishanyufu** [comment]
客气啦。有问题能解决我会尽量解决的。

**Comment by longforrich** [comment]
设置了
```
    "remote.extensionKind": {
        "beishanyufu.ime-and-cursor": ["ui"]
    }
```
插件可以在远程连接开发工作了，问题解决！

**Comment by beishanyufu** [comment]
#


> 设置了
> 
> ```
>     "remote.extensionKind": {
>         "beishanyufu.ime-and-cursor": ["ui"]
>     }
> ```
> 
> 插件可以在远程连接开发工作了，问题解决！

太好了！
